# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "演示站点"
weight = 1
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 2
